[features]
seeds = false
[programs.devnet]
myepicproject = "FHbBQDoHrMos9tKTMt9C5N2hqgM7Xhm9wRtkNLfFV1iB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mferrara625/.config/solana/id.json"

[test]
startup_wait = 100000

[scripts]
test = "node tests/myepicproject.js"
