[features]
seeds = false
[programs.localnet]
myepicproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mferrara625/.config/solana/id.json"

[test]
startup_wait = 100000

[scripts]
test = "node tests/myepicproject.js"
